/********************************************************************
* BMyRecCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BMyRecCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBMyRecCint();
extern void G__cpp_setup_inheritanceBMyRecCint();
extern void G__cpp_setup_typetableBMyRecCint();
extern void G__cpp_setup_memvarBMyRecCint();
extern void G__cpp_setup_globalBMyRecCint();
extern void G__cpp_setup_memfuncBMyRecCint();
extern void G__cpp_setup_funcBMyRecCint();
extern void G__set_cpp_environmentBMyRecCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BMyReco.h"
#include "BMyRecoMC.h"
#include "BMyRecoBEvt.h"
#include "BMyRecoReco.h"
#include "BMyRecIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BMyRecCintLN_TClass;
extern G__linked_taginfo G__BMyRecCintLN_TBuffer;
extern G__linked_taginfo G__BMyRecCintLN_TMemberInspector;
extern G__linked_taginfo G__BMyRecCintLN_TObject;
extern G__linked_taginfo G__BMyRecCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__BMyRecCintLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__BMyRecCintLN_string;
extern G__linked_taginfo G__BMyRecCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BMyRecCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BMyRecCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BMyRecCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BMyRecCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BMyRecCintLN_TFile;
extern G__linked_taginfo G__BMyRecCintLN_MParContainer;
extern G__linked_taginfo G__BMyRecCintLN_MInputStreamID;
extern G__linked_taginfo G__BMyRecCintLN_MParList;
extern G__linked_taginfo G__BMyRecCintLN_MTask;
extern G__linked_taginfo G__BMyRecCintLN_TH1F;
extern G__linked_taginfo G__BMyRecCintLN_TH2F;
extern G__linked_taginfo G__BMyRecCintLN_TProfile;
extern G__linked_taginfo G__BMyRecCintLN_BEvent;
extern G__linked_taginfo G__BMyRecCintLN_BEventMask;
extern G__linked_taginfo G__BMyRecCintLN_BGeomTel;
extern G__linked_taginfo G__BMyRecCintLN_BChannelMask;
extern G__linked_taginfo G__BMyRecCintLN_BExtractedImpulseTel;
extern G__linked_taginfo G__BMyRecCintLN_BJoinExtractedImpulseTel;
extern G__linked_taginfo G__BMyRecCintLN_BExtractedHeader;
extern G__linked_taginfo G__BMyRecCintLN_BJoinExtractedHeader;
extern G__linked_taginfo G__BMyRecCintLN_BMyReco;
extern G__linked_taginfo G__BMyRecCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__BMyRecCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BMyRecCintLN_BMCEvent;
extern G__linked_taginfo G__BMyRecCintLN_BMyRecoMC;
extern G__linked_taginfo G__BMyRecCintLN_BMyRecoBEvt;
extern G__linked_taginfo G__BMyRecCintLN_BRecParameters;
extern G__linked_taginfo G__BMyRecCintLN_BMyRecoReco;

/* STUB derived class for protected member access */
