/********************************************************************
* BRecCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BRecCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBRecCint();
extern void G__cpp_setup_inheritanceBRecCint();
extern void G__cpp_setup_typetableBRecCint();
extern void G__cpp_setup_memvarBRecCint();
extern void G__cpp_setup_globalBRecCint();
extern void G__cpp_setup_memfuncBRecCint();
extern void G__cpp_setup_funcBRecCint();
extern void G__set_cpp_environmentBRecCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BReconstruct.h"
#include "BRecParameters.h"
#include "BReconstructMuon.h"
#include "BRecQualify.h"
#include "BRecQuality.h"
#include "BRecIncl.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BRecCintLN_TClass;
extern G__linked_taginfo G__BRecCintLN_TBuffer;
extern G__linked_taginfo G__BRecCintLN_TMemberInspector;
extern G__linked_taginfo G__BRecCintLN_TObject;
extern G__linked_taginfo G__BRecCintLN_TString;
extern G__linked_taginfo G__BRecCintLN_ROOT;
extern G__linked_taginfo G__BRecCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BRecCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BRecCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BRecCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BRecCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BRecCintLN_TFile;
extern G__linked_taginfo G__BRecCintLN_MParContainer;
extern G__linked_taginfo G__BRecCintLN_MInputStreamID;
extern G__linked_taginfo G__BRecCintLN_MParList;
extern G__linked_taginfo G__BRecCintLN_MTask;
extern G__linked_taginfo G__BRecCintLN_ROOTcLcLMath;
extern G__linked_taginfo G__BRecCintLN_ROOTcLcLMathcLcLMinimizer;
extern G__linked_taginfo G__BRecCintLN_ROOTcLcLMathcLcLFunctor;
extern G__linked_taginfo G__BRecCintLN_ROOTcLcLMathcLcLInterpolator;
extern G__linked_taginfo G__BRecCintLN_BEvent;
extern G__linked_taginfo G__BRecCintLN_BEventMask;
extern G__linked_taginfo G__BRecCintLN_BGeomTel;
extern G__linked_taginfo G__BRecCintLN_BSecInteraction;
extern G__linked_taginfo G__BRecCintLN_BRecParameters;
extern G__linked_taginfo G__BRecCintLN_BChannelMask;
extern G__linked_taginfo G__BRecCintLN_BMuonCriterionParameters;
extern G__linked_taginfo G__BRecCintLN_BReconstruct;
extern G__linked_taginfo G__BRecCintLN_vectorlEBReconstructcLcLpaircOallocatorlEBReconstructcLcLpairgRsPgR;
extern G__linked_taginfo G__BRecCintLN_reverse_iteratorlEvectorlEBReconstructcLcLpaircOallocatorlEBReconstructcLcLpairgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BRecCintLN_TH2F;
extern G__linked_taginfo G__BRecCintLN_BReconstructMuon;
extern G__linked_taginfo G__BRecCintLN_BSourceEAS;
extern G__linked_taginfo G__BRecCintLN_BRecQualify;
extern G__linked_taginfo G__BRecCintLN_BRecQuality;

/* STUB derived class for protected member access */
